# Generated by Django 4.2.3 on 2023-07-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_course_image_alter_course_trailer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Exam', 'Exam'), ('Topic', 'Topic')], default='Exam', max_length=32),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.exam',),
        ),
    ]
