# Generated by Django 4.2.3 on 2023-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_question_topic_exam_exam_type_delete_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
